### ISSUE TITLE
Hardware: Update the position of some components

### ISSUE THREAD

**Issue by comesanha** [spacelab-ufsc/eps-re#10]
From LTC3833

- Place the ceramic Cvcc capacitor (C110/C111/C22/C23 in circuit) as close as possible to INTVCC and PGND pins.

- The CB capacitor (C20/C21/C108/C109 in circuit) should be as close as possible to BOOST and SW pins.

- Place small-signal components as close to their respective pins as possible. Give priority to VOSNS+/VOSNS–, SENSE+/SENSE–, ITH, RT and VRNG pins.

- Use sufficient isolation when routing a clock signal into MODE/PLLIN pin so that the clock does not couple into sensitive small-signal pins.

- Filter the Vin input to the LTC3833 with a simple RC filter close to the pin. The RC filter should be referenced to signal ground.

**Comment by rebeccaquintino** [comment]
- [x] Place the ceramic Cvcc capacitor (C110/C111/C22/C23 in circuit) as close as possible to INTVCC and PGND pins.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/14a93131-6aa8-4707-b984-014c04bc5da7)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/acd008f0-ad25-483a-bca8-b2a11023ae65)

- [x] The CB capacitor (C20/C21/C108/C109 in circuit) should be as close as possible to BOOST and SW pins.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/b5a3dd10-f93c-4f00-83d9-d4a772578a2c)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/6673f9f2-9cae-4556-a8ea-0a603d497375)

- [x] Place small-signal components as close to their respective pins as possible. Give priority to VOSNS+/VOSNS–, SENSE+/SENSE–, ITH, RT and VRNG pins.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/3db25ec8-9864-4c12-becc-8a6ff5583a17)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/0ab2116a-c1cf-466e-a3bf-4b3b1de37abc)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/75d52d65-74cc-470d-9600-7be99d8f531f)

- [x] Use sufficient isolation when routing a clock signal into MODE/PLLIN pin so that the clock does not couple into sensitive small-signal pins.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/f16592b2-46bf-4600-ae94-77ca811f7f12)

- [x] Filter the Vin input to the LTC3833 with a simple RC filter close to the pin. The RC filter should be referenced to signal ground.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/444de70d-13ee-4471-8fc6-68122c5a0df1)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/1d134c93-1674-494f-bd3b-ddbfbe1ed11f)
